### ISSUE TITLE
Small question: parallellization

### ISSUE THREAD

**Issue by ignace-computing** [CliMA/EnsembleKalmanProcesses.jl#148]
Hi!

I have a small question, if I may.
Have you included any parallelization (over the particles) in this package?

Thanks a lot,
Ignace

**Comment by odunbar** [comment]
Ensemble methods are completely parallelizable as you say. This is not part of the source code, because the parallellism occurs outside of the EKP process. However you can use our examples as guidelines

### Case 1: All within Julia
In simple examples, e.g. `examples/Lorenz/` we run a forward model `GModel` within a for loop over the ensemble
```julia
for i in 1:N_iter
        params_i = get_u_final(ekiobj)
       g_ens = GModel.run_G_ensemble(params_i, lorenz_settings_G)
end
```
Every iteration here is independent and immediately parallelizable with e.g. Julia's `@distributed` macro from the `Distributed` package.

### Case 2: HPC interface
If you have something more intensive such as found with HPC interfacing (e.g. if your model is a large parallel simulation). We suggest using something more along the lines of an interleaving of EKP update runs, and model runs. In our `example/ClimateMachine` we provide an example based on SLURM workload managers in HPC. Here, one runs the outer loop over ensembles in `sbatch` scripts
```csh
# First call to calibrate.jl will create the ensemble files from the priors
id_init_ens=$(sbatch --parsable -A esm ekp_init_calibration.sbatch)
for it in $(seq 1 1 $n_it)
do
# Parallel runs of forward model
if [ "$it" = "1" ]; then
    id_ens_array=$(sbatch --parsable --kill-on-invalid-dep=yes -A esm --dependency=afterok:$id_init_ens --array=1-$n ekp_single_cm_run.sbatch $it)
else
    id_ens_array=$(sbatch --parsable --kill-on-invalid-dep=yes -A esm --dependency=afterok:$id_ek_upd --array=1-$n ekp_single_cm_run.sbatch $it)
fi
id_ek_upd=$(sbatch --parsable --kill-on-invalid-dep=yes -A esm --dependency=afterok:$id_ens_array --export=n=$n ekp_cont_calibration.sbatch $it)
done
```
Here a dependency tree is setup in SLURM, which iterates calls to the scripts `ekp_single_cm_run.sbatch` (which runs the model on HPC) and `ekp_cont_calibration.sbatch` (which performs the EKI update).
