### ISSUE TITLE
New Docs pages request

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#153]
New Pages
- [x] DataContainers
- [x] failure handling in the different particle methods - Ignacio
- [x] Use cases HPC vs "local julia" implementation (see e.g. the response in #148) (pmap/distributed vs SLURM & new file interface) - Haakon/Melanie/Ollie
- [x] Sparse EKI documentation - (Jinlong)
- [x] Localization and sampling error correction - Ignacio
- [x] Extra info on SEC and localization example with Lorenz 96 (a commented version of the current test would work) - Eviatar
- [x] Recommended settings of "bells and whistles" (localization/regularization/inflation...)

Please add suggestions below!

**Comment by odunbar** [comment]
@haakon-e  see the 2nd point here. I've added you to the issue

**Comment by ilopezgp** [comment]
Localization documentation will be added in #189.

We still need the documentation of SparseEKI, with a warning sign about its lack of robustness unless issues discussed in #146 are fixed. @jinlong83 

Anything other than localization that we want to add as bells and whistles, @odunbar ? Since we do not have more in the source code, maybe best to leave it at that for now.

**Comment by odunbar** [comment]
Completed with JOSS paper submission
