### ISSUE TITLE
Breaking changes in version 1.1.6+ violate semantic versioning

### ISSUE THREAD

**Issue by bgroenks96** [CliMA/EnsembleKalmanProcesses.jl#393]
Hi all,

It recently came to my attention (after updating) that breaking changes were made to the `EnsembleKalmanProcess` type as part of the effort to redesign the observation API and add minibatching. Namely, the fields for the observation mean and covariance were replaced by the new API.

I realize that struct fields are generally considered non-public APIs, but in this case, there were previously no methods that provided access to these fields. Thus, I would argue removing or modifying it counts as a potential breaking change for downstream code (it broke my package, at least). At the very least, it should be a minor version change, I think.

I guess it's too late now to do much about it, but since this package is relatively mature (and very nice!), I would hope for a bit more consideration when making breaking changes in the future.

Thanks for your work and continued development of the package!

**Comment by odunbar** [comment]
Hi Brian, thanks for using the code. I apologise for this, the update was indeed supposed to be a major breaking update (i.e. v2.0.0 not a patch!) - and was very much a mistake on my end at the time.

We are very soon (on the order of days) in moving to v2.0.0, where we shall move to using the "current best defaults" as preset, rather than vanilla options. So we are currently debating whether to do something to patch the patch, or just to jump to v2 and put this all in the past. 

Thanks a bunch for raising the issue, and please continue to do so if you find other points that would help you in your work moving forward. I'll ping this thread when we move forward

**Comment by bgroenks96** [comment]
It would definitely be too much hassle to try and retract or change versions from the Julia repository so the two options would probably be:

1) Create patch 1.1.7 which reverts to 1.1.5 with any additional necessary changes backported in and then moving to 2.0
2) Just move to 2.0 and leave it as-is, as you suggest.

I think both are OK; I would go with option 2 if option 1 takes more than 20 minutes of work.
